version: '7.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8080:8080"
    environment:
      - COMPOSE_BAKE=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_SHOW_SQL=${JPA_SHOW_SQL:-false}
      - SERVER_TOMCAT_MAX_THREADS=${TOMCAT_MAX_THREADS:-200}
    cpus: "1.0"
    mem_limit: 512m
