services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8081:8081"
    environment:
      - SERVER_TOMCAT_MAX_THREADS=${TOMCAT_MAX_THREADS:-200}
      - CACHE_LOG_INTERVAL=${CACHE_LOG_INTERVAL}
    cpus: "1.0"
    mem_limit: 1024m
